apiVersion: v1
items:
- kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: capacity-planner
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - nodes
    - resourcequotas
    verbs:
    - list
- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: capacity-planners
  subjects:
  - kind: ServiceAccount
    name: capacity-planner
    namespace: capacity-planner
  roleRef:
    kind: ClusterRole
    name: capacity-planner
    apiGroup: rbac.authorization.k8s.io
kind: List
metadata: {}
